---
output:
  html_document:
    css: www/styles.css
    anchor_sections: FALSE
    includes:
      in_header: "header_manual.html"

params:
  year_curr: 2023 # Current year of sampling
  all_years: TRUE # If FALSE, only reports on year_curr; TRUE reports on all years
  spp_list: "FQAI" # If FQAI, matches species in database against OH EPA spp. list. If DB, matches against tlu_WetlndSpeciesList 
  
---

```{r setup, include = F}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.kable.NA = '', scipen = 100)
```

```{r imports, include = FALSE}
library(wetlandHTLN)
library(tidyverse)
library(knitr)
library(kableExtra)
#library(htmltools) # for tagList to iterate on a code chunk. Not sure I'm going to need this yet.

importData()
year_curr = params$year_curr
year_range = if(params$all_years == TRUE){2008:year_curr} else {year_curr}

spp_list <- params$spp_list

#arglist <- list(park = park, years = year)

# locs <- do.call(getPlots, arglist) |>
#   select(LocationID) |> unique() |> c() #|> as.character()
```


Wetland Quality Control checking for CUVA and `r paste(year_curr, collapse = ", ")` {.tabset .tabset-pills}
---

```{r, include = F, results = 'hide'}
source('QC_VIBI_report_compile.R')
```

```{r eval = loc_include, results = "asis"}
cat("### Locations {.tabset}", "\n\n")

check_null_print(tbl_locid_typos, 4, "LocationID")

check_null_print(tbl_feat_typos, 4, "FeatureType")

check_null_print(tbl_feat_symb, 4, "FeatureID")

check_null_print(tbl_miss_domveg, 4, "DomVeg missing")

check_null_print(tbl_conflict_domveg, 4, "DomVeg conflict")

check_null_print(tbl_area_error, 4, "AreaHA vs TotMods")

check_null_print(tbl_intern_check, 4, "Intern vs TotalMods")



```

```{r eval = pev_include, results = "asis"}
cat("### Sampling Periods/Events {.tabset}", "\n\n")

check_null_print(tbl_miss_periods, 4, "miss PeriodID")

check_null_print(tbl_miss_samp_evs, 4, "miss EventID")

check_null_print(tbl_odd_dates1, 4, "StartDate1")

check_null_print(tbl_odd_dates2, 4, "StartDate2")


```


```{r eval = herb_include, results = "asis"}
cat("### VIBI Herbs {.tabset}", "\n\n")

check_null_print(tbl_herb_blanks, 4, "Herb blanks")

check_null_print(tbl_herb_dups, 4, "Duplicate spp.")

check_null_print(tbl_herb_miss, 4, "Missing spp.")

check_null_print(tbl_herb_once, 4, "One-timers")
```


```{r eval = woody_include, results = "asis"}
cat("### VIBI Woody {.tabset}", "\n\n")

check_null_print(tbl_woody_fid_check, 4, "FeatureIDs")

check_null_print(tbl_woody_blanks, 4, "Woody blanks")

check_null_print(tbl_woody9s, 4, "-9999 counts")

check_null_print(tbl_diamid_check, 4, "DiamIDs")



```

